import React from 'react'
import './card.css'
import Button from '../Button/Button'
import CodeIcon from '@material-ui/icons/Code';
import GradeIcon from '@material-ui/icons/Grade';
import DeviceHubIcon from '@material-ui/icons/DeviceHub';
import ChatBubbleOutlineIcon from '@material-ui/icons/ChatBubbleOutline';
// import img1 from '../../asset/myImage.jpg'


function card({ updatedAt, createdAt, name, img }) {

    const updated = updatedAt.split('T')[0]
    const created = createdAt.split('T')[0]

    return (
        <div className="wrapper">
            <div className="card">
                <div className="card__header">
                    <div className="card__header__left">
                        <img src={img} alt="images" />
                        <p>{name}</p>
                    </div>

                    <div className="card__header__right">
                        <Button label="Files" icon={<CodeIcon />} />
                        <Button label="Forks" icon={<DeviceHubIcon />} />
                        <Button label="Comments" icon={<ChatBubbleOutlineIcon />} />
                        <Button label="Stars" icon={<GradeIcon />} />
                    </div>
                </div>

                <div className="card__body">
                    <div className="card__body__left">
                        <span >Created at : {created} </span>
                        <span className="card__body__left__span">Last updated : {updated}</span>
                    </div>
                    <h3>Generated by </h3>
                    <Button label="Stars" icon={<GradeIcon />} />
                </div>
            </div>
        </div>
    )
}

export default card
